# Generated by Django 3.2.2 on 2022-11-07 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='total_duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
