# Generated by Django 3.2.2 on 2022-11-08 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0003_auto_20221108_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginlogout',
            name='attendance_of',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app2.attendance'),
            preserve_default=False,
        ),
    ]
