# Generated by Django 3.2.2 on 2022-11-08 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0004_loginlogout_attendance_of'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='session_key',
        ),
        migrations.AddField(
            model_name='loginlogout',
            name='session_key',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
