# Generated by Django 3.2.2 on 2022-11-08 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0005_auto_20221108_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='present',
            field=models.BooleanField(default=False),
        ),
    ]
