# Generated by Django 3.2.2 on 2022-11-09 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0008_auto_20221108_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginlogout',
            name='login_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
