# Generated by Django 3.2.2 on 2022-11-09 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0009_auto_20221109_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='logout_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='working_date',
            field=models.DateTimeField(null=True),
        ),
    ]
