# Generated by Django 3.2.2 on 2022-11-09 16:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0010_auto_20221109_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='duration',
            field=models.DurationField(default=datetime.timedelta),
        ),
    ]
