# Generated by Django 3.2.2 on 2022-11-10 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0011_alter_profile_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='buffer_time_login',
            field=models.DurationField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='buffer_time_logout',
            field=models.DurationField(null=True),
        ),
    ]
